ALTER TABLE projects ADD COLUMN IF NOT EXISTS context TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS architecture TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS challenges TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS results TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS future_improvements TEXT;

ALTER TABLE educations ADD COLUMN IF NOT EXISTS context TEXT;
ALTER TABLE educations ADD COLUMN IF NOT EXISTS key_subjects TEXT[] DEFAULT '{}';
ALTER TABLE educations ADD COLUMN IF NOT EXISTS personal_contribution TEXT;

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS mission_context TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS achievements TEXT[] DEFAULT '{}';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS methods TEXT[] DEFAULT '{}';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS results TEXT;
