-- IA Mistral en local (JoyTrain/Bora) + MManima : explications hold/hedge/carry, pitch honnête.
BEGIN;

-- JoyTrain : coach IA precise (Mistral, local)
UPDATE projects SET features = ARRAY['Suivi d''entraînement complet : exercices, programmes, cardio et records personnels', 'Coach IA « Bora » propulsé par Mistral, en local — sans dépendre d''une IA propriétaire payante', 'Scan d''un repas par photo pour estimer automatiquement les apports', 'Journal nutrition adossé à une vraie base alimentaire et ses macros', 'Couche sociale : amis, posts, messagerie et notifications en temps réel', 'Mode hors-ligne : on enregistre ses séances sans réseau, tout se synchronise ensuite', 'Graphiques de progression et atlas musculaire interactif', 'Prête pour les stores (TestFlight iOS et Google Play)']::text[], updated_at = now() WHERE slug = 'joytrain';

-- Bora : Mistral en local, sans IA proprietaire payante
UPDATE projects SET short_description = 'Le moteur d''IA qui fait répondre le coach JoyTrain à partir de vraies sources reconnues — propulsé par Mistral, en local, sans dépendre d''une IA propriétaire payante.', architecture = 'Un pipeline qui collecte des sources fiables (santé, nutrition, science), les indexe par le sens (embeddings bge-m3, base vectorielle pgvector) et combine recherche par mots-clés et par sens pour retrouver le bon passage. La génération des réponses s''appuie sur Mistral exécuté en local : aucune dépendance à une IA propriétaire payante, et les données restent maîtrisées.', features = ARRAY['Tourne en local sur Mistral, sans dépendre d''une IA propriétaire payante', 'Réponses appuyées sur de vraies sources reconnues (santé, nutrition, science)', 'Retrouve l''information la plus pertinente pour chaque question posée', 'Tient compte du contexte de l''utilisateur pour mieux cibler la réponse', 'Recherche hybride : comprend le sens ET retrouve les termes techniques exacts', 'Chaque réponse reste rattachée à sa source d''origine', 'Tourne en local, sans dépendre d''une IA propriétaire payante', 'Brique IA de l''écosystème JoyTrain (app + moteur Bora + site vitrine)']::text[], updated_at = now() WHERE slug = 'bora-rag-joytrain';

-- MManima : contenu pitch + honnete
UPDATE projects SET short_description = 'Une appli qui rend l''investissement crypto tenable : au lieu de parier sur le sens du marché, elle protège ton capital des krachs — tu places ton argent et tu peux ne plus le surveiller.', long_description = 'Une appli qui rend l''investissement crypto tenable : au lieu de parier sur le sens du marché, elle protège ton capital des krachs — tu places ton argent et tu peux ne plus le surveiller.', context = 'Soyons honnêtes : personne ne sait vraiment où va le marché. Chercher à le prédire, c''est parier — et le parieur perd sur la durée. Je voulais l''inverse : investir en crypto sans y passer mes journées et sans jouer à la loterie. L''idée de MManima est simple : ne pas deviner le marché, mais s''en protéger. Une couverture automatique qui sort des krachs, et du carry qui rapporte régulièrement. Tu investis, et tu peux passer à autre chose.', goal = 'Rendre l''investissement crypto serein et tenable : protéger le capital des effondrements et générer un rendement régulier, sans pari directionnel ni surveillance permanente.', features = ARRAY['Protection automatique anti-krach : une couverture (hedge) te met à l''abri quand le marché plonge', 'Carry : un revenu régulier capté sans parier sur le sens du marché', 'Investis et oublie : plus besoin de surveiller les cours en permanence', 'Suivi en temps réel de ton portefeuille Binance (spot, futures, épargne)', 'Alertes techniques personnalisables (RSI, MACD, Bollinger, moyennes mobiles)', 'Simulation et backtests pour tester une stratégie avant d''engager le moindre euro', 'Connexion sécurisée à ton compte, clés API chiffrées']::text[], architecture = 'Une app mobile (Flutter) connectée à un backend (FastAPI + PostgreSQL + Redis) relié à Binance. À côté, un vrai laboratoire de machine learning (PyTorch, modèles TFT et CNN-LSTM, backtests rigoureux) qui m''a servi à trancher une question simple : peut-on prédire le marché ? La réponse, mesurée honnêtement, est non — ce qui a orienté tout le produit vers la protection plutôt que la prédiction.', results = 'Le fond du sujet : prédire le marché est quasi impossible, et s''y essayer revient à parier — un jeu perdant sur le long terme. La valeur est ailleurs : se protéger. Sur un backtest 2021-2026 (panier BTC/ETH/XRP/SOL, données Binance réelles, frais inclus), la crypto couverte a fait +34 %/an, contre +10 %/an en achat simple et +12 %/an pour le S&P 500, en évitant l''essentiel du krach 2022 (voir le graphe). À lire comme un résultat sur une période passée favorable, pas une promesse — mais le principe tient : investir, être protégé, et ne plus avoir à regarder.', updated_at = now() WHERE slug = 'mmanima';

-- MManima : 3 sections explicatives (hold / hedge / carry), visibles
DELETE FROM project_sections WHERE project_id = (SELECT id FROM projects WHERE slug = 'mmanima');
INSERT INTO project_sections (project_id, title, subtitle, body, section_type, layout, display_order, is_visible)
SELECT id, 'Buy & Hold : tout miser sur la hausse', NULL, 'Acheter et garder, c''est le réflexe de départ : on parie que le prix va monter. Quand le marché grimpe, on gagne ; quand il s''effondre — et la crypto s''effondre fort, parfois −70 % —, on encaisse toute la chute.

Sur un cycle complet, c''est un grand huit éprouvant, et souvent moins rentable qu''on ne l''imagine : sur 2021-2026, l''achat simple a même fait moins bien que la Bourse classique, pour un risque bien plus grand.', 'La base', 'text_only', 1, true FROM projects WHERE slug = 'mmanima'
ON CONFLICT (project_id, lower(title)) DO UPDATE SET body = EXCLUDED.body, section_type = EXCLUDED.section_type, display_order = EXCLUDED.display_order, is_visible = true, updated_at = now();
INSERT INTO project_sections (project_id, title, subtitle, body, section_type, layout, display_order, is_visible)
SELECT id, 'Le hedge : une assurance anti-krach', NULL, 'Le hedge, c''est une assurance pour ton portefeuille. On suit une moyenne mobile du prix : quand le prix passe en dessous (signe de faiblesse), on se met à l''abri en stablecoin ; quand il repasse au-dessus, on rachète.

Résultat : on évite l''essentiel des krachs, au prix de quelques faux signaux. Le hedge ne cherche pas à gagner plus — il cherche à perdre moins quand ça tourne mal. Et c''est ça qui change tout : tu investis, tu es protégé, et tu n''as plus à surveiller.', 'La protection', 'text_only', 2, true FROM projects WHERE slug = 'mmanima'
ON CONFLICT (project_id, lower(title)) DO UPDATE SET body = EXCLUDED.body, section_type = EXCLUDED.section_type, display_order = EXCLUDED.display_order, is_visible = true, updated_at = now();
INSERT INTO project_sections (project_id, title, subtitle, body, section_type, layout, display_order, is_visible)
SELECT id, 'Le carry : un revenu régulier, quel que soit le marché', NULL, 'Le carry, c''est le « loyer » d''une position : un revenu qu''on touche juste en la détenant, grâce à un écart de rendement — indépendamment de la hausse ou de la baisse.

En crypto, on détient au comptant et on vend un contrat à terme de la même valeur : on devient neutre au prix et on encaisse le financement. Lent mais régulier, peu volatil — la brique tranquille du portefeuille.', 'Le revenu', 'text_only', 3, true FROM projects WHERE slug = 'mmanima'
ON CONFLICT (project_id, lower(title)) DO UPDATE SET body = EXCLUDED.body, section_type = EXCLUDED.section_type, display_order = EXCLUDED.display_order, is_visible = true, updated_at = now();

COMMIT;
