ALTER TABLE educations ADD COLUMN IF NOT EXISTS program_summary TEXT;
ALTER TABLE educations ADD COLUMN IF NOT EXISTS program_distribution TEXT;

ALTER TABLE courses ADD COLUMN IF NOT EXISTS formation_year VARCHAR(80);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS semester VARCHAR(80);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS hours VARCHAR(80);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS ects VARCHAR(160);

INSERT INTO course_categories (name, description, skills_summary, display_order) VALUES
('Sciences pour l’ingénieur', 'Enseignements destinés à consolider les bases scientifiques nécessaires à la modélisation, l’optimisation, l’analyse statistique et la compréhension des systèmes d’ingénierie.', 'Mathématiques pour l’ingénieur, modélisation, optimisation, statistiques, probabilités, physique appliquée, systèmes de communication, analyse scientifique.', 201),
('Sciences et techniques pour les transitions', 'Enseignements centrés sur les enjeux environnementaux, numériques et énergétiques, avec une approche orientée transition écologique, sobriété, écoconception et technologies durables.', 'Écoconception, analyse du cycle de vie, environnement numérique, transition énergétique, développement durable, IA, cybersécurité, traitement de données, mesure environnementale.', 202),
('Projet multidisciplinaire et fil rouge', 'Enseignements et projets permettant de mettre en pratique les compétences techniques à travers des réalisations progressives, multidisciplinaires et professionnalisantes.', 'Microcontrôleurs, développement embarqué, projet fil rouge, IHM, Android, LabVIEW, ingénierie dirigée par les modèles, propriété intellectuelle, travail en équipe, gestion de projet.', 203),
('Architectures, électroniques et systèmes embarqués', 'Enseignements centrés sur l’électronique analogique et numérique, les capteurs, les architectures embarquées, les systèmes asservis, les microprocesseurs, l’électronique de commande et la compatibilité électromagnétique.', 'Électronique analogique, électronique numérique, capteurs, conditionnement de signal, architectures numériques, microprocesseurs, HIL, systèmes asservis, CEM, moteurs électriques, électronique de commande.', 204),
('Informatique, logiciels embarqués et IA', 'Enseignements centrés sur la programmation, les logiciels embarqués, les systèmes critiques, le temps réel, l’intelligence artificielle embarquée, la vision et le traitement d’images.', 'Logiciel embarqué, systèmes temps réel, logiciels critiques, IA embarquée, vision embarquée, traitement d’images, Android, algorithmique, programmation, validation logicielle.', 205),
('Réseaux, sécurité et fiabilité des systèmes embarqués', 'Enseignements centrés sur les réseaux, la sécurité, la cryptographie, la validation, les méthodes formelles et la qualification des systèmes embarqués.', 'Réseaux de terrain, cybersécurité, cryptographie, sécurité embarquée, méthodes formelles, validation, qualification système, sûreté de fonctionnement.', 206),
('Technologies des systèmes embarqués', 'Enseignements liés aux technologies matérielles, procédés intégrés, communication sans fil, modélisation industrielle et analyse des marchés des systèmes embarqués.', 'Technologies intégrées, salle blanche, communication sans fil, modélisation de systèmes électroniques industriels, produits et marchés, R&D, systèmes embarqués industriels.', 207),
('Anglais, management et sciences humaines', 'Enseignements liés à l’anglais, à la communication professionnelle, au management, à l’innovation, au droit, aux sciences humaines, à la RSE et à la compréhension de l’entreprise.', 'Anglais technique, communication professionnelle, management de projet, innovation, stratégie, négociation, droit, finances, RSE, management interculturel.', 208),
('Séquence professionnelle et alternance', 'Périodes en entreprise permettant d’appliquer les compétences acquises à l’école, de développer une posture professionnelle et de progresser sur des missions techniques réelles.', 'Alternance, expérience professionnelle, autonomie, mission technique, rapport professionnel, soutenance, tutorat, analyse de situation, compétences métier.', 209)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    skills_summary = EXCLUDED.skills_summary,
    display_order = EXCLUDED.display_order,
    updated_at = now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Sciences pour l’ingénieur')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_SCI_01', 'Outils mathématiques pour la modélisation', '1re année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences pour l’ingénieur — 3 ECTS', 'Étude des outils mathématiques nécessaires à la modélisation de systèmes physiques, électroniques et informatiques dans un contexte d’ingénierie.', 'Mathématiques appliquées, modélisation, analyse de systèmes, calcul scientifique.', (SELECT id FROM category), 1),
('ESIEE_SCI_02', 'Fondamentaux de mathématiques pour l’ingénieur 1', '1re année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences pour l’ingénieur — 3 ECTS', 'Renforcement des fondamentaux mathématiques nécessaires à l’analyse, au raisonnement scientifique et à la résolution de problèmes d’ingénierie.', 'Mathématiques pour l’ingénieur, raisonnement scientifique, calcul, résolution de problèmes.', (SELECT id FROM category), 2),
('ESIEE_SCI_03', 'Méthodes d’optimisation', '1re année', 'Semestre 2', '30 h', 'Inclus dans le bloc Sciences pour l’ingénieur — 3 ECTS', 'Introduction aux méthodes d’optimisation utilisées pour formuler, analyser et résoudre des problèmes techniques ou industriels.', 'Optimisation, modélisation, résolution de problèmes, méthodes numériques.', (SELECT id FROM category), 3),
('ESIEE_SCI_04', 'Fondamentaux de mathématiques pour l’ingénieur 2', '1re année', 'Semestre 2', '30 h', 'Inclus dans le bloc Sciences pour l’ingénieur — 3 ECTS', 'Approfondissement des notions mathématiques utiles à la modélisation, à l’analyse de systèmes et à la résolution de problèmes scientifiques.', 'Mathématiques appliquées, modélisation, analyse, calcul scientifique.', (SELECT id FROM category), 4),
('ESIEE_SCI_05', 'Statistiques et probabilités', '2e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences pour l’ingénieur — 3 ECTS', 'Étude des probabilités et statistiques appliquées à l’analyse de données, à l’incertitude, à la modélisation et à la prise de décision en ingénierie.', 'Statistiques, probabilités, analyse de données, incertitude, modélisation.', (SELECT id FROM category), 5),
('ESIEE_SCI_06', 'Fondements des systèmes de communication', '2e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences pour l’ingénieur — 3 ECTS', 'Introduction aux principes scientifiques et techniques des systèmes de communication utilisés dans les systèmes électroniques et numériques.', 'Systèmes de communication, signal, transmission, réseaux, communication numérique.', (SELECT id FROM category), 6)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Sciences et techniques pour les transitions')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_TR_01', 'Écoconception et analyse du cycle de vie', '1re année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences et techniques pour la transition — 3 ECTS', 'Étude des principes d’écoconception et d’analyse du cycle de vie afin d’évaluer l’impact environnemental d’un produit ou d’un système technique.', 'Écoconception, analyse du cycle de vie, développement durable, impact environnemental, conception responsable.', (SELECT id FROM category), 1),
('ESIEE_TR_02', 'Environnement numérique de l’ingénieur', '1re année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences et techniques pour la transition — 3 ECTS', 'Découverte de l’environnement numérique de travail de l’ingénieur, des outils numériques et des méthodes utilisées pour concevoir, documenter, analyser et collaborer.', 'Outils numériques, environnement d’ingénierie, documentation, collaboration, méthodes de travail.', (SELECT id FROM category), 2),
('ESIEE_TR_03', 'Physique pour la transition énergétique', '1re année', 'Semestre 2', '30 h', 'Inclus dans le bloc Sciences et techniques pour la transition — 3 ECTS', 'Étude des principes physiques liés à l’énergie, aux systèmes énergétiques et aux enjeux de transition énergétique.', 'Physique appliquée, transition énergétique, énergie, systèmes physiques, modélisation.', (SELECT id FROM category), 3),
('ESIEE_TR_04', 'Algorithmique et programmation pour l’ingénieur', '1re année', 'Semestre 2', '30 h', 'Inclus dans le bloc Sciences et techniques pour la transition — 3 ECTS', 'Introduction à l’algorithmique et à la programmation appliquées aux problématiques d’ingénierie.', 'Algorithmique, programmation, résolution de problèmes, structuration du code, logique informatique.', (SELECT id FROM category), 4),
('ESIEE_TR_05', 'Introduction aux réseaux, à la sécurité et à la cybersécurité', '2e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences et techniques pour les transitions — 3 ECTS', 'Introduction aux réseaux informatiques, aux principes de sécurité numérique et aux enjeux de cybersécurité dans les systèmes connectés.', 'Réseaux, cybersécurité, sécurité informatique, protocoles, systèmes connectés.', (SELECT id FROM category), 5),
('ESIEE_TR_06', 'Traitement et analyse de données', '2e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences et techniques pour les transitions — 3 ECTS', 'Méthodes de collecte, traitement, analyse et interprétation de données dans un contexte scientifique et technique.', 'Analyse de données, traitement de données, statistiques appliquées, visualisation, interprétation.', (SELECT id FROM category), 6),
('ESIEE_TR_07', 'Dérèglement climatique et pollutions 1 : modèles, impacts', '2e année', 'Semestre 2', '30 h', 'Inclus dans le bloc Sciences et techniques pour les transitions — 3 ECTS', 'Étude des modèles, impacts et enjeux liés au dérèglement climatique et aux pollutions.', 'Développement durable, climat, modélisation, analyse d’impact, transition écologique.', (SELECT id FROM category), 7),
('ESIEE_TR_08', 'Introduction à l’IA', '2e année', 'Semestre 2', '30 h', 'Inclus dans le bloc Sciences et techniques pour les transitions — 3 ECTS', 'Introduction aux concepts fondamentaux de l’intelligence artificielle et à ses applications dans les systèmes numériques et industriels.', 'Intelligence artificielle, apprentissage automatique, analyse de données, algorithmique, modélisation.', (SELECT id FROM category), 8),
('ESIEE_TR_09', 'Du capteur au cloud : mesure pour l’environnement', '3e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences et techniques pour les transitions — 3 ECTS', 'Étude d’une chaîne complète de mesure environnementale, depuis l’acquisition par capteur jusqu’à la transmission et l’exploitation des données dans le cloud.', 'Capteurs, acquisition de données, objets connectés, cloud, mesure environnementale, traitement de données.', (SELECT id FROM category), 9),
('ESIEE_TR_10', 'Dérèglement climatique et pollutions 2 : atelier DD', '3e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sciences et techniques pour les transitions — 3 ECTS', 'Atelier de développement durable appliqué notamment aux transports et aux véhicules électriques, avec analyse des enjeux environnementaux et techniques.', 'Développement durable, RSE, véhicules électriques, analyse d’impact, transition énergétique.', (SELECT id FROM category), 10)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Projet multidisciplinaire et fil rouge')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_PRJ_01', 'Microcontrôleurs 1', '1re année', 'Semestre 1', '30 h', '2 ECTS', 'Première approche des microcontrôleurs, de leur programmation et de leur utilisation pour piloter des entrées/sorties et réaliser des fonctions embarquées simples.', 'Microcontrôleurs, C embarqué, GPIO, programmation bas niveau, électronique embarquée.', (SELECT id FROM category), 1),
('ESIEE_PRJ_02', 'Microcontrôleurs 2', '1re année', 'Semestre 2', '30 h', '2 ECTS', 'Approfondissement de la programmation des microcontrôleurs et de l’intégration de fonctions embarquées plus avancées.', 'Microcontrôleurs, timers, interruptions, ADC, PWM, programmation embarquée, intégration matérielle/logicielle.', (SELECT id FROM category), 2),
('ESIEE_PRJ_03', 'IHM / Android', '2e année', 'Semestre 1', '20 h', 'Inclus dans le bloc Projet multidisciplinaire — 2 ECTS', 'Conception d’interfaces homme-machine et développement d’applications Android dans le cadre de projets techniques.', 'IHM, Android, interface utilisateur, développement mobile, ergonomie.', (SELECT id FROM category), 3),
('ESIEE_PRJ_04', 'Atelier LabVIEW', '2e année', 'Semestre 1', '10 h', 'Inclus dans le bloc Projet multidisciplinaire — 2 ECTS', 'Utilisation de LabVIEW pour l’acquisition de données, la mesure, l’automatisation ou le pilotage de systèmes.', 'LabVIEW, acquisition de données, instrumentation, automatisation, mesure.', (SELECT id FROM category), 4),
('ESIEE_PRJ_05', 'Ingénierie dirigée par les modèles', '2e année', 'Semestre 2', '30 h', '2 ECTS', 'Introduction à l’ingénierie dirigée par les modèles pour concevoir, structurer et générer des systèmes logiciels ou techniques à partir de modèles abstraits.', 'Modélisation, ingénierie dirigée par les modèles, architecture logicielle, conception système.', (SELECT id FROM category), 5),
('ESIEE_PRJ_06', 'Fil rouge', '3e année', 'Semestre 1', '125 h', 'Inclus dans le bloc Projet multidisciplinaire — 8 ECTS', 'Projet long permettant de mobiliser les compétences acquises en électronique, logiciel embarqué, systèmes physiques, management de projet et validation autour d’une réalisation technique complète.', 'Projet d’ingénierie, systèmes embarqués, conception, intégration, validation, travail en équipe, documentation technique.', (SELECT id FROM category), 6),
('ESIEE_PRJ_07', 'Brevet / Propriété intellectuelle', '3e année', 'Semestre 1', '15 h', 'Inclus dans le bloc Projet multidisciplinaire — 8 ECTS', 'Introduction aux notions de propriété intellectuelle, brevet, protection de l’innovation et valorisation technique.', 'Propriété intellectuelle, brevet, innovation, protection technique, valorisation.', (SELECT id FROM category), 7)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Architectures, électroniques et systèmes embarqués')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_ARCH_01', 'Électronique numérique', '1re année', 'Semestre 1', '24 h', 'Inclus dans le bloc Architectures & Électroniques embarquées — 4 ECTS', 'Étude des circuits logiques, des architectures numériques et des principes de conception électronique numérique.', 'Électronique numérique, logique combinatoire, logique séquentielle, architectures numériques, circuits logiques.', (SELECT id FROM category), 1),
('ESIEE_ARCH_02', 'Électronique analogique', '1re année', 'Semestre 1', '28 h', 'Inclus dans le bloc Architectures & Électroniques embarquées — 4 ECTS', 'Étude des circuits analogiques, du conditionnement de signal, des composants électroniques et des fonctions d’acquisition.', 'Électronique analogique, composants électroniques, conditionnement de signal, mesures, acquisition.', (SELECT id FROM category), 2),
('ESIEE_ARCH_03', 'Systèmes asservis, HIL', '1re année', 'Semestre 1', '28 h', 'Inclus dans le bloc Architectures & Électroniques embarquées — 4 ECTS', 'Étude des systèmes asservis et introduction aux approches Hardware-in-the-Loop pour tester et valider des systèmes commandés.', 'Systèmes asservis, HIL, automatique, validation, commande, tests.', (SELECT id FROM category), 3),
('ESIEE_ARCH_04', 'Capteurs et électronique de conditionnement', '1re année', 'Semestre 2', '28 h', 'Inclus dans le bloc Architectures & Électroniques embarquées — 4 ECTS', 'Étude des capteurs et des circuits de conditionnement permettant d’adapter les signaux mesurés à une chaîne d’acquisition.', 'Capteurs, conditionnement de signal, électronique analogique, acquisition, mesures physiques.', (SELECT id FROM category), 4),
('ESIEE_ARCH_05', 'Architectures numériques', '1re année', 'Semestre 2', '24 h', 'Inclus dans le bloc Architectures & Électroniques embarquées — 4 ECTS', 'Étude des architectures numériques utilisées dans les systèmes embarqués et électroniques.', 'Architectures numériques, logique numérique, systèmes embarqués, architecture matérielle.', (SELECT id FROM category), 5),
('ESIEE_ARCH_06', 'Physique appliquée', '1re année', 'Semestre 2', '28 h', 'Inclus dans le bloc Architectures & Électroniques embarquées — 4 ECTS', 'Application des principes physiques aux systèmes électroniques, capteurs, mesures et systèmes embarqués.', 'Physique appliquée, systèmes physiques, mesures, modélisation, électronique.', (SELECT id FROM category), 6),
('ESIEE_ARCH_07', 'Systèmes asservis, HIL', '2e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Électroniques embarqués avancées — 4 ECTS', 'Approfondissement des systèmes asservis et des méthodes de validation Hardware-in-the-Loop pour systèmes embarqués.', 'Systèmes asservis, HIL, validation système, commande, modélisation.', (SELECT id FROM category), 7),
('ESIEE_ARCH_08', 'Microprocesseur avancé', '2e année', 'Semestre 1', '20 h', 'Inclus dans le bloc Électroniques embarqués avancées — 4 ECTS', 'Étude avancée des microprocesseurs, de leur architecture et de leur intégration dans les systèmes embarqués.', 'Microprocesseurs, architecture processeur, systèmes embarqués, programmation bas niveau.', (SELECT id FROM category), 8),
('ESIEE_ARCH_09', 'Compatibilité électromagnétique', '2e année', 'Semestre 1', '20 h', 'Inclus dans le bloc Électroniques embarqués avancées — 4 ECTS', 'Étude des perturbations électromagnétiques, de leur propagation, de leur impact sur les systèmes électroniques et des règles de conception associées.', 'CEM, compatibilité électromagnétique, perturbations, intégrité du signal, conception électronique.', (SELECT id FROM category), 9),
('ESIEE_ARCH_10', 'Moteurs électriques et électroniques de commande', '2e année', 'Semestre 2', '30 h', 'Inclus dans le bloc Ingénierie des systèmes embarqués — 5 ECTS', 'Étude des moteurs électriques, de leur commande et des circuits électroniques associés à la conversion et au pilotage d’énergie.', 'Moteurs électriques, électronique de commande, PWM, électronique de puissance, conversion d’énergie.', (SELECT id FROM category), 10)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Informatique, logiciels embarqués et IA')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_SW_01', 'Système temps réel', '2e année', 'Semestre 2', '28 h', 'Inclus dans le bloc Ingénierie des systèmes embarqués — 5 ECTS', 'Étude des systèmes soumis à des contraintes temporelles, avec notions d’ordonnancement, tâches, interruptions, synchronisation et déterminisme.', 'Temps réel, RTOS, ordonnancement, tâches, interruptions, synchronisation, déterminisme.', (SELECT id FROM category), 1),
('ESIEE_SW_02', 'Objets connectés', '2e année', 'Semestre 2', '22 h', 'Inclus dans le bloc Ingénierie des systèmes embarqués — 5 ECTS', 'Étude de systèmes connectés combinant capteurs, électronique, logiciel embarqué et communication réseau.', 'Objets connectés, IoT, capteurs, communication, logiciel embarqué, acquisition de données.', (SELECT id FROM category), 2),
('ESIEE_SW_03', 'Particularités des transports aéronautiques, guidés et automobiles', '3e année', 'Semestre 1', '24 h', 'Inclus dans le bloc Logiciels embarqués — 5 ECTS', 'Étude des contraintes propres aux systèmes embarqués utilisés dans les transports aéronautiques, guidés et automobiles.', 'Systèmes embarqués critiques, transport, contraintes industrielles, sûreté de fonctionnement, validation.', (SELECT id FROM category), 3),
('ESIEE_SW_04', 'Logiciels critiques temps réel embarqué', '3e année', 'Semestre 1', '24 h', 'Inclus dans le bloc Logiciels embarqués — 5 ECTS', 'Développement et validation de logiciels embarqués soumis à des contraintes temps réel et de criticité.', 'Logiciels critiques, temps réel embarqué, validation logicielle, sûreté, programmation embarquée.', (SELECT id FROM category), 4),
('ESIEE_SW_05', 'IA embarquée', '3e année', 'Semestre 1', '22 h', 'Inclus dans le bloc Logiciels embarqués — 5 ECTS', 'Étude des méthodes d’intelligence artificielle adaptées aux systèmes embarqués et aux contraintes de ressources.', 'IA embarquée, machine learning embarqué, optimisation, contraintes mémoire, traitement embarqué.', (SELECT id FROM category), 5),
('ESIEE_SW_06', 'Vision, traitement d’images embarquées', '3e année', 'Semestre 1', '25 h', 'Inclus dans le bloc Logiciels embarqués — 5 ECTS', 'Étude des méthodes de vision et de traitement d’images intégrées dans des systèmes embarqués.', 'Vision embarquée, traitement d’images, acquisition, filtrage, analyse d’images, systèmes embarqués.', (SELECT id FROM category), 6)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Réseaux, sécurité et fiabilité des systèmes embarqués')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_SEC_01', 'Réseaux de terrain', '2e année', 'Semestre 2', '20 h', 'Inclus dans le bloc Ingénierie des systèmes embarqués — 5 ECTS', 'Étude des réseaux utilisés dans les systèmes industriels et embarqués pour connecter capteurs, actionneurs, contrôleurs et calculateurs.', 'Réseaux de terrain, protocoles industriels, communication embarquée, systèmes distribués.', (SELECT id FROM category), 1),
('ESIEE_SEC_02', 'Cryptographie', '3e année', 'Semestre 1', '26 h', 'Inclus dans le bloc Sécurité et fiabilité des systèmes embarqués — 5 ECTS', 'Étude des principes de cryptographie utilisés pour sécuriser les communications, les données et les systèmes numériques.', 'Cryptographie, sécurité, chiffrement, protocoles sécurisés, protection des données.', (SELECT id FROM category), 2),
('ESIEE_SEC_03', 'Sécurité des applications embarquées', '3e année', 'Semestre 1', '24 h', 'Inclus dans le bloc Sécurité et fiabilité des systèmes embarqués — 5 ECTS', 'Étude des vulnérabilités, menaces et méthodes de sécurisation propres aux applications embarquées.', 'Sécurité embarquée, cybersécurité, applications embarquées, analyse de vulnérabilités, protection système.', (SELECT id FROM category), 3),
('ESIEE_SEC_04', 'Méthodes formelles', '3e année', 'Semestre 1', '24 h', 'Inclus dans le bloc Sécurité et fiabilité des systèmes embarqués — 5 ECTS', 'Introduction aux méthodes formelles permettant de spécifier, vérifier et valider rigoureusement le comportement de systèmes critiques.', 'Méthodes formelles, vérification, validation, spécification, systèmes critiques.', (SELECT id FROM category), 4),
('ESIEE_SEC_05', 'Validation et qualification système', '3e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Sécurité et fiabilité des systèmes embarqués — 5 ECTS', 'Étude des méthodes de validation, qualification et vérification de systèmes embarqués dans un contexte industriel.', 'Validation système, qualification, tests, vérification, sûreté de fonctionnement, documentation technique.', (SELECT id FROM category), 5)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Technologies des systèmes embarqués')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_TECH_01', 'Process et technologies intégrées', '3e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Technologies des systèmes embarqués — 6 ECTS', 'Découverte des procédés et technologies intégrées, notamment en environnement salle blanche, utilisés dans la fabrication de composants et systèmes électroniques.', 'Technologies intégrées, salle blanche, microtechnologies, procédés industriels, fabrication électronique.', (SELECT id FROM category), 1),
('ESIEE_TECH_02', 'Communication sans fil', '3e année', 'Semestre 1', '24 h', 'Inclus dans le bloc Technologies des systèmes embarqués — 6 ECTS', 'Étude des principes de communication sans fil utilisés dans les systèmes embarqués et connectés.', 'Communication sans fil, radiofréquence, protocoles, systèmes connectés, transmission.', (SELECT id FROM category), 2),
('ESIEE_TECH_03', 'Modélisation de systèmes électroniques industriels', '3e année', 'Semestre 1', '40 h', 'Inclus dans le bloc Technologies des systèmes embarqués — 6 ECTS', 'Modélisation de systèmes électroniques industriels pour analyser, simuler et concevoir des solutions embarquées complexes.', 'Modélisation, systèmes électroniques industriels, simulation, conception système, analyse.', (SELECT id FROM category), 3),
('ESIEE_TECH_04', 'Produits - Marchés - Perspectives', '3e année', 'Semestre 1', '18 h', 'Inclus dans le bloc Technologies des systèmes embarqués — 6 ECTS', 'Analyse des produits, marchés et perspectives liés aux technologies des systèmes embarqués.', 'Analyse marché, innovation, stratégie produit, technologies embarquées, veille technologique.', (SELECT id FROM category), 4)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Anglais, management et sciences humaines')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_HUM_01', 'Anglais 1', '1re année', 'Semestre 1', '30 h', '1 ECTS', 'Développement des compétences en anglais dans un contexte académique, professionnel et technique.', 'Anglais, compréhension, expression orale, communication technique.', (SELECT id FROM category), 1),
('ESIEE_HUM_02', 'Compétences & Carrières S1', '1re année', 'Semestre 1', '12 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 2 ECTS', 'Développement des compétences professionnelles, réflexion sur le parcours, les objectifs et l’insertion dans le monde de l’entreprise.', 'Projet professionnel, compétences, carrière, insertion, communication.', (SELECT id FROM category), 2),
('ESIEE_HUM_03', 'Projet d’intégration', '1re année', 'Semestre 1', '14 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 2 ECTS', 'Projet visant à faciliter l’intégration dans la formation, le travail en équipe et la compréhension des attentes de l’école.', 'Travail en équipe, intégration, communication, organisation.', (SELECT id FROM category), 3),
('ESIEE_HUM_04', 'Découverte de l’entreprise', '1re année', 'Semestre 1', '16 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 2 ECTS', 'Découverte du fonctionnement de l’entreprise, de ses métiers, de son organisation et de ses enjeux.', 'Entreprise, organisation, management, culture professionnelle.', (SELECT id FROM category), 4),
('ESIEE_HUM_05', 'Anglais 2', '1re année', 'Semestre 2', '30 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Approfondissement de l’anglais technique et professionnel.', 'Anglais technique, communication professionnelle, rédaction, expression orale.', (SELECT id FROM category), 5),
('ESIEE_HUM_06', 'Compétences & Carrières S2', '1re année', 'Semestre 2', '10 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Poursuite de la construction du projet professionnel et valorisation des compétences.', 'Projet professionnel, valorisation des compétences, communication, insertion.', (SELECT id FROM category), 6),
('ESIEE_HUM_07', 'Management de projet', '1re année', 'Semestre 2', '16 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Introduction aux méthodes de management de projet, à l’organisation, au suivi et au pilotage d’activités techniques.', 'Management de projet, organisation, planification, suivi, travail en équipe.', (SELECT id FROM category), 7),
('ESIEE_HUM_08', 'Finances et structures des coûts', '1re année', 'Semestre 2', '16 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Introduction aux notions financières et aux structures de coûts dans un contexte d’entreprise et de projet.', 'Finances, coûts, gestion, entreprise, prise de décision.', (SELECT id FROM category), 8),
('ESIEE_HUM_09', 'Anglais 3', '2e année', 'Semestre 1', '30 h', '1 ECTS', 'Renforcement de l’anglais appliqué aux contextes techniques, professionnels et internationaux.', 'Anglais professionnel, anglais technique, communication, présentation orale.', (SELECT id FROM category), 9),
('ESIEE_HUM_10', 'Compétences & Carrières S3', '2e année', 'Semestre 1', '10 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 2 ECTS', 'Développement de la posture professionnelle et des compétences liées à la carrière.', 'Carrière, compétences professionnelles, communication, projet professionnel.', (SELECT id FROM category), 10),
('ESIEE_HUM_11', 'Improvisation théâtrale', '2e année', 'Semestre 1', '6 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 2 ECTS', 'Exercices d’expression orale, d’aisance relationnelle et de communication à travers l’improvisation.', 'Expression orale, communication, aisance, prise de parole.', (SELECT id FROM category), 11),
('ESIEE_HUM_12', 'Management de l’innovation technologique / Stratégie d’entreprise / Économie de l’innovation', '2e année', 'Semestre 1', '14 h', 'Inclus dans le bloc Être innovant et créatif', 'Enseignement au choix portant sur l’innovation, la stratégie d’entreprise ou l’économie de l’innovation.', 'Innovation, stratégie, créativité, économie, management.', (SELECT id FROM category), 12),
('ESIEE_HUM_13', 'Négocier et vendre / Recruter un équipier / Diriger et décider', '2e année', 'Semestre 1', '12 h', 'Inclus dans le bloc Être communicant et négociateur', 'Enseignement au choix visant à développer des compétences de communication, de négociation, de recrutement ou de prise de décision.', 'Négociation, communication, décision, management, leadership.', (SELECT id FROM category), 13),
('ESIEE_HUM_14', 'Anglais 4', '2e année', 'Semestre 2', '30 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Approfondissement de l’anglais professionnel et technique.', 'Anglais professionnel, anglais technique, rédaction, expression orale.', (SELECT id FROM category), 14),
('ESIEE_HUM_15', 'Compétences & Carrières S4', '2e année', 'Semestre 2', '12 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Valorisation des compétences, préparation à l’évolution professionnelle et structuration du parcours d’ingénieur.', 'Carrière, valorisation, projet professionnel, communication.', (SELECT id FROM category), 15),
('ESIEE_HUM_16', 'Introduction au droit', '2e année', 'Semestre 2', '12 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Introduction aux notions juridiques utiles à l’ingénieur et à l’activité en entreprise.', 'Droit, responsabilité, entreprise, contrats, propriété intellectuelle.', (SELECT id FROM category), 16),
('ESIEE_HUM_17', 'Simulation de gestion d’entreprise / Simulation de gestion de projet', '2e année', 'Semestre 2', '18 h', 'Inclus dans le bloc Business game', 'Mise en situation autour de la gestion d’entreprise ou de projet afin de comprendre les décisions économiques, organisationnelles et stratégiques.', 'Gestion d’entreprise, gestion de projet, stratégie, prise de décision, management.', (SELECT id FROM category), 17),
('ESIEE_HUM_18', 'Anglais 5', '3e année', 'Semestre 1', '30 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Renforcement de la communication en anglais dans un contexte professionnel, technique et international.', 'Anglais professionnel, anglais technique, communication internationale, présentation.', (SELECT id FROM category), 18),
('ESIEE_HUM_19', 'Compétences & Carrières S5', '3e année', 'Semestre 1', '20 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Préparation à l’entrée dans la vie professionnelle, valorisation du parcours et consolidation de la posture d’ingénieur.', 'Carrière, insertion professionnelle, communication, posture ingénieur.', (SELECT id FROM category), 19),
('ESIEE_HUM_20', 'Management interculturel', '3e année', 'Semestre 1', '10 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Étude des enjeux de collaboration, communication et management dans des contextes multiculturels.', 'Management interculturel, communication internationale, collaboration, diversité culturelle.', (SELECT id FROM category), 20),
('ESIEE_HUM_21', 'Sciences sociales autour des enjeux DD et RSE', '3e année', 'Semestre 1', '12 h', 'Inclus dans le bloc Anglais, management et sciences humaines — 3 ECTS', 'Analyse des enjeux de développement durable, de responsabilité sociétale des entreprises et de leur impact sur les organisations.', 'RSE, développement durable, sciences sociales, responsabilité, entreprise.', (SELECT id FROM category), 21)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH category AS (SELECT id FROM course_categories WHERE name = 'Séquence professionnelle et alternance')
INSERT INTO courses (code, title, formation_year, semester, hours, ects, description, skills_summary, category_id, display_order) VALUES
('ESIEE_ALT_01', 'Séquence professionnelle S1', '1re année', 'Semestre 1', 'Non applicable', '15 ECTS', 'Période professionnelle en entreprise permettant de découvrir l’environnement industriel, les missions techniques et l’organisation du travail en alternance.', 'Alternance, entreprise, intégration, observation, compétences professionnelles.', (SELECT id FROM category), 1),
('ESIEE_ALT_02', 'Exercices d’alternance S1', '1re année', 'Semestre 1', 'Non applicable', 'Inclus dans le bloc professionnel S1', 'Travaux liés à l’analyse de l’expérience en entreprise et à la formalisation des compétences développées pendant l’alternance.', 'Analyse professionnelle, rédaction, retour d’expérience, posture d’apprenti ingénieur.', (SELECT id FROM category), 2),
('ESIEE_ALT_03', 'Séquence professionnelle S2', '1re année', 'Semestre 2', 'Non applicable', '15 ECTS', 'Période professionnelle en entreprise permettant de poursuivre la montée en compétences sur des missions techniques.', 'Alternance, mission technique, autonomie, intégration en équipe, compétences métier.', (SELECT id FROM category), 3),
('ESIEE_ALT_04', 'Rapport de situation professionnelle', '1re année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S2', 'Rédaction d’un rapport permettant de présenter le contexte professionnel, l’entreprise, les missions réalisées et les compétences développées.', 'Rédaction technique, analyse de mission, synthèse, communication professionnelle.', (SELECT id FROM category), 4),
('ESIEE_ALT_05', 'Soutenance du rapport de situation professionnelle', '1re année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S2', 'Présentation orale du rapport de situation professionnelle devant un jury ou des encadrants.', 'Présentation orale, soutenance, communication, argumentation.', (SELECT id FROM category), 5),
('ESIEE_ALT_06', 'Animation du tutorat S2', '1re année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S2', 'Suivi et échanges entre l’apprenti, l’école et l’entreprise afin d’accompagner la progression professionnelle.', 'Tutorat, suivi professionnel, communication, progression.', (SELECT id FROM category), 6),
('ESIEE_ALT_07', 'Séquence professionnelle S3', '2e année', 'Semestre 1', 'Non applicable', '15 ECTS', 'Poursuite de l’alternance avec montée en responsabilité et application des compétences techniques en entreprise.', 'Alternance, autonomie, montée en responsabilité, mission technique, compétences métier.', (SELECT id FROM category), 7),
('ESIEE_ALT_08', 'Études scientifiques et techniques', '2e année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S4', 'Travail d’analyse technique et scientifique en lien avec les missions réalisées en entreprise.', 'Analyse technique, démarche scientifique, documentation, résolution de problèmes.', (SELECT id FROM category), 8),
('ESIEE_ALT_09', 'Séquence professionnelle S4', '2e année', 'Semestre 2', 'Non applicable', '15 ECTS', 'Période professionnelle en entreprise centrée sur des missions techniques plus avancées et professionnalisantes.', 'Alternance, autonomie, mission technique, responsabilité, intégration professionnelle.', (SELECT id FROM category), 9),
('ESIEE_ALT_10', 'Rapport de mission technique', '2e année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S4', 'Rédaction d’un rapport détaillant une mission technique réalisée en entreprise, ses objectifs, méthodes, résultats et apports.', 'Rapport technique, analyse de mission, documentation, synthèse, validation.', (SELECT id FROM category), 10),
('ESIEE_ALT_11', 'Soutenance du rapport de mission technique', '2e année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S4', 'Présentation orale d’une mission technique réalisée en entreprise, avec mise en avant du contexte, des choix techniques et des résultats.', 'Soutenance, communication orale, argumentation technique, présentation.', (SELECT id FROM category), 11),
('ESIEE_ALT_12', 'Animation du tutorat S4', '2e année', 'Semestre 2', 'Non applicable', 'Inclus dans le bloc professionnel S4', 'Suivi de l’alternance et accompagnement de la progression de l’apprenti ingénieur entre école et entreprise.', 'Tutorat, progression professionnelle, communication, analyse réflexive.', (SELECT id FROM category), 12),
('ESIEE_ALT_13', 'Séquence professionnelle et alternance', '3e année', 'Semestre 1', 'Non applicable', 'À compléter selon les données disponibles', 'Période professionnelle de dernière année permettant de consolider les compétences d’ingénieur, d’approfondir les missions techniques et de préparer la transition vers le métier cible.', 'Alternance, autonomie, responsabilité, mission d’ingénieur, professionnalisation, compétences métier.', (SELECT id FROM category), 13)
ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, formation_year=EXCLUDED.formation_year, semester=EXCLUDED.semester, hours=EXCLUDED.hours, ects=EXCLUDED.ects, description=EXCLUDED.description, skills_summary=EXCLUDED.skills_summary, category_id=EXCLUDED.category_id, display_order=EXCLUDED.display_order, updated_at=now();

WITH esiee_educations AS (
    SELECT e.id
    FROM educations e
    LEFT JOIN schools s ON s.id = e.school_id
    WHERE lower(COALESCE(s.name, '')) LIKE '%esiee%'
),
esiee_courses AS (
    SELECT id FROM courses WHERE code LIKE 'ESIEE\_%' ESCAPE '\'
)
INSERT INTO education_courses (education_id, course_id)
SELECT esiee_educations.id, esiee_courses.id
FROM esiee_educations
CROSS JOIN esiee_courses
ON CONFLICT DO NOTHING;

UPDATE educations
SET context = COALESCE(NULLIF(context, ''), 'Cette formation d’ingénieur en systèmes embarqués s’inscrit dans mon objectif de devenir ingénieur capable de concevoir, développer, intégrer et valider des systèmes électroniques et logiciels embarqués. Elle relie les sciences de l’ingénieur, l’électronique, le logiciel embarqué, le temps réel, les capteurs, les réseaux de terrain, la sécurité et l’expérience en entreprise.'),
    program_summary = COALESCE(NULLIF(program_summary, ''), 'La formation d’ingénieur en systèmes embarqués à ESIEE Paris combine des enseignements scientifiques, électroniques, informatiques et professionnels. Le programme associe cours, travaux dirigés, travaux pratiques, projets multidisciplinaires et missions en entreprise. Il permet de développer des compétences en électronique embarquée, microcontrôleurs, logiciel embarqué, temps réel, capteurs, systèmes physiques, réseaux de terrain, sécurité, validation, innovation et management de projet.'),
    program_distribution = COALESCE(NULLIF(program_distribution, ''), 'Ingénierie embarquée, transitions, R&D : 22,5%
Informatique & logiciels embarqués : 20,2%
Sciences humaines, anglais & management : 20,2%
Électronique, capteurs & systèmes physiques : 19,1%
Sciences de l’ingénieur, mathématiques et physique : 10,1%
Projet fil rouge : 7,9%')
WHERE id IN (
    SELECT e.id
    FROM educations e
    LEFT JOIN schools s ON s.id = e.school_id
    WHERE lower(COALESCE(s.name, '')) LIKE '%esiee%'
);

UPDATE educations
SET context = COALESCE(NULLIF(context, ''), 'La formation UTC renforce mon socle en informatique, mathématiques, systèmes, robotique et technologies avancées. Elle complète mon parcours GEII en élargissant mes compétences vers l’algorithmique, les bases de données, les réseaux, les systèmes d’exploitation, l’optimisation, la robotique, le temps réel et l’analyse critique du rôle de l’ingénieur.'),
    program_summary = COALESCE(NULLIF(program_summary, ''), 'Le programme suivi à l’UTC m’a permis de structurer un socle scientifique et informatique solide, avec des UV en algorithmique, programmation orientée objet, systèmes d’exploitation, bases de données, réseaux, systèmes temps réel, robotique, optimisation, anglais et sciences humaines.')
WHERE id IN (
    SELECT e.id
    FROM educations e
    LEFT JOIN schools s ON s.id = e.school_id
    WHERE lower(COALESCE(s.name, '')) LIKE '%utc%'
       OR lower(COALESCE(s.name, '')) LIKE '%technologie de compi%'
);
